# Site settings
title: Rowen
email: rowen0820@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Keep It Simple & Stupid
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dualpoly.com" # the base hostname & protocol for your site
twitter_username: rowen0820
github_username:  Winlang

# Build settings
#markdown: kramdown
markdown: redcarpet

paginate: 4

author: Rowen

gems: [jekyll-paginate]
